"""update chat/message models

Revision ID: 66309e479c30
Revises: 218d8ecce949
Create Date: 2026-01-21 14:08:43.989135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '66309e479c30'
down_revision: Union[str, Sequence[str], None] = '218d8ecce949'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'title')
    # ### end Alembic commands ###
